# Generated by Django 4.2.5 on 2023-10-01 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instituicao_ano", models.CharField(default="", max_length=150)),
                ("texto", models.TextField(default="")),
                ("enunciado", models.TextField(default="")),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("respondida", models.BooleanField(default=False)),
                (
                    "assunto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questoes.assunto",
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questoes.disciplina",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assunto",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questoes.disciplina"
            ),
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(default="")),
                ("correta", models.BooleanField(default=False)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="questoes.questao",
                    ),
                ),
            ],
        ),
    ]
