# Generated by Django 4.2.5 on 2023-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0003_remove_alternativa_user_remove_questao_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questao",
            name="ordem",
        ),
        migrations.AddField(
            model_name="questao",
            name="acertou",
            field=models.BooleanField(default=False),
        ),
    ]
