# Generated by Django 4.2.5 on 2023-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0004_questao_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questao",
            name="usuario",
        ),
        migrations.AddField(
            model_name="questao",
            name="questoes_certas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questao",
            name="questoes_erradas",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
