# Generated by Django 4.2.5 on 2023-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0007_resposta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resposta",
            name="questoes_certas",
        ),
        migrations.RemoveField(
            model_name="resposta",
            name="questoes_erradas",
        ),
        migrations.AddField(
            model_name="resposta",
            name="certa",
            field=models.BooleanField(default=False),
        ),
    ]
