# Generated by Django 4.2.5 on 2023-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0009_remove_resposta_certa"),
    ]

    operations = [
        migrations.AddField(
            model_name="resposta",
            name="certa",
            field=models.BooleanField(default=False),
        ),
    ]
