# Generated by Django 4.2.5 on 2023-12-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0012_resposta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resposta",
        ),
    ]
