# Generated by Django 4.2.5 on 2023-12-08 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0014_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="resposta",
            name="questao",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questoes.questao",
            ),
        ),
    ]
