# Generated by Django 4.2.5 on 2023-12-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0015_resposta_questao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resposta",
            name="questao",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="questoes.questao",
            ),
        ),
    ]
