# Generated by Django 4.2.5 on 2023-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0016_alter_resposta_questao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="questoes_certas",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="questoes_erradas",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="acertos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="erros",
            field=models.IntegerField(default=0),
        ),
    ]
