# Generated by Django 4.2.5 on 2023-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questoes", "0020_alter_userprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questao",
            name="ordem",
        ),
        migrations.RemoveField(
            model_name="questao",
            name="questoes_certas",
        ),
        migrations.RemoveField(
            model_name="questao",
            name="questoes_erradas",
        ),
        migrations.RemoveField(
            model_name="questao",
            name="respondida",
        ),
    ]
