# Generated by Django 4.2.5 on 2023-12-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=11)),
                ("Endereco", models.CharField(max_length=200)),
                ("foto", models.ImageField(upload_to="media/perfil/img/")),
            ],
        ),
    ]
