# Generated by Django 4.2.5 on 2023-12-08 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="perfil",
            name="Endereco",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(blank=True, upload_to="perfil/img/"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="telefone",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
