# Generated by Django 4.2.5 on 2023-12-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_perfil_user_alter_perfil_endereco_alter_perfil_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="Endereco",
        ),
        migrations.AlterField(
            model_name="perfil",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(upload_to="core/media/perfil/img/"),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="telefone",
            field=models.CharField(max_length=11),
        ),
        migrations.AddField(
            model_name="perfil",
            name="endereco",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
