# Generated by Django 4.2.5 on 2023-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_perfil_endereco_alter_perfil_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(upload_to="perfil/img/"),
        ),
    ]
