# Generated by Django 4.2.5 on 2023-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="endereco",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="telefone",
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
