# Generated by Django 4.2.5 on 2023-12-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_profile_endereco_profile_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="core/img/personcircle.svg", upload_to="perfil/img"
            ),
        ),
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
