# Generated by Django 4.2.5 on 2023-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_profile_email_alter_profile_image_delete_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="static/core/img/personcircle.svg", upload_to="perfil/img"
            ),
        ),
    ]
