# Generated by Django 4.2.5 on 2023-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="personcircle.png", upload_to="perfil/img"),
        ),
    ]
