# Generated by Django 4.2.5 on 2023-10-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Conteudo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250)),
                (
                    "assunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materiais.assunto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default="", max_length=100)),
                ("imagem", models.ImageField(upload_to="static/img")),
            ],
        ),
        migrations.CreateModel(
            name="Materiais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("link", models.URLField()),
                ("textotitulo", models.CharField(max_length=250)),
                ("texto", models.TextField()),
                ("referencias", models.TextField()),
                (
                    "conteudo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materiais.conteudo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conteudo",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="materiais.disciplina"
            ),
        ),
        migrations.AddField(
            model_name="assunto",
            name="disciplina",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="materiais.disciplina"
            ),
        ),
    ]
