# Generated by Django 4.2.5 on 2023-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="imagem",
            field=models.ImageField(upload_to="materiais/static/materiais/img/"),
        ),
    ]
