# Generated by Django 4.2.5 on 2023-12-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0002_alter_disciplina_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disciplina",
            name="imagem",
        ),
    ]
