# Generated by Django 4.2.5 on 2023-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiais", "0004_disciplina_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplina",
            name="imagem",
            field=models.FileField(upload_to="materiais/static/materiais/img/"),
        ),
    ]
