# Generated by Django 4.2 on 2023-12-28 22:15

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("revisao", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="verso",
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
